/* Topic mapping file converted from THERENAME */
/* Converted by eHelp Corporation's Help-to-Source */

#define License_Agreement     	0xb
#define File_menu     	0xd
#define Options     	0xe
#define Information     	0xf
#define Undo_Last_Rename     	0x10
#define Exit     	0x11
#define Your_Favorites_menu     	0x12
#define Add_this_directory_to_your_favorites     	0x13
#define How_to_obtain_last_version_and_information     	0xa
#define Help_menu     	0x15
#define Windows_Explorer_Context_Menu     	0x16
#define Drag_and_Drop_with_Windows_Explorer     	0x17
#define Contextuel_menu_in_file's_list     	0x18
#define How_it_works_when_using_Modify_prefix_or_Modify_extension     	0x19
#define Others_options     	0x1a
#define Organize_your_favorites     	0x14
#define Conflicts     	0x20
#define Example_1     	0x21
#define Example_2     	0x22
#define Example_3     	0x23
#define What_will_be_the_news?     	0x25
#define Change_files_attributes     	0x26
#define Stop_process     	0x27
#define When_using_Free_Form     	0x29
#define Change_file's_date_and_time     	0x2a
#define What's_new?     	0x2b
#define Search_high_counter     	0x2c
#define Contextual_menu_in_directories_list     	0x2d
#define How_to_search_for_a_file_in_the_file_list     	0x2e
#define Tell_THE_Rename_what_to_do_when_you_double_click_on_the_files_list     	0x2f
#define Have_your_own_file_filters_selection     	0x30
#define Make_multiple_file_selection     	0x31
#define Refresh_file_list     	0x28
#define Save_settings     	0x33
#define Save_as_...     	0x34
#define Preview_the_processe     	0x35
#define Find_conflicts     	0x36
#define Open_THE_Rename_with_settings     	0x37
#define Make_recursive_search_to_rename_files     	0x38
#define Print_Directory     	0x39
#define Change_sort_order_in_the_file_list     	0x3a
#define View_history     	0x3b
#define Open_settings_...     	0x32
#define Disk_menu     	0x3d
#define Format_Drive_and_floppies     	0x3e
#define Set_volume_label     	0x3f
#define Map_network_drive     	0x40
#define Disconnect_network_drive     	0x41
#define How_to_copy_files_to_multiple_directories     	0x43
#define How_to_define_the_startup_directory     	0x44
#define go_back_to_a_precedent_visited_directory     	0x45
#define File_Find...     	0x3c
#define Shortcuts     	0x6f
#define Menu_bar     	0x71
#define select_all_button     	0x72
#define unselect_button     	0x73
#define reverse_order_selection_button     	0x74
#define step_button     	0x75
#define start_button     	0x76
#define preview_button     	0x77
#define Search_and_Replace_in_Prefix_and/or_Extension     	0x6e
#define drop_files_button     	0x79
#define Up_button_1     	0x7a
#define root_button     	0x7b
#define history_button     	0x7c
#define file_filter_button     	0x7d
#define recursive_button     	0x7e
#define directory_list_1     	0x7f
#define file_list     	0x80
#define splitter_bar     	0x81
#define rename_manually_button     	0x78
#define modify_prefix_list     	0x83
#define modify_extension_list     	0x84
#define prefix_zone     	0x85
#define extension_zone     	0x86
#define sample_tab     	0x87
#define info_tab     	0x88
#define information_bar     	0x89
#define file_traited     	0x8a
#define files_selected     	0x8b
#define column_headers     	0x82
#define system_date     	0x8d
#define system_time     	0x8e
#define Edit_menu     	0x8f
#define Bugs     	0x90
#define Drag_some_files_from_Windows_Explorer_to_the_multiple_copy_button     	0x92
#define Select_the_same_option_for_prefix_and_extension     	0x93
#define Run_menu     	0x94
#define Select_All     	0x95
#define number_of_files     	0x8c
#define Invert_selection     	0x97
#define Step     	0x98
#define Start     	0x99
#define Preview     	0x9a
#define Recursive_mode     	0x9c
#define View_menu     	0x9d
#define Refresh     	0x9e
#define How_to_Create_a_group_of_directories     	0x9f
#define Unselect     	0x96
#define Mapped_drives     	0xa1
#define Add_picture's_width_and_height_in_filename     	0xa2
#define yéK     	0xa5
#define How_to_validate_filenames_?     	0xa6
#define How_to_se_counters_with_letters_?     	0xa7
#define Cyclic_selections     	0xa8
#define How_to_replace_with_"nothing"_?     	0xa9
#define Rename_manually     	0xab
#define Directory_list_2     	0xac
#define files_list     	0xad
#define Toolbar     	0xae
#define Option_for_prefix     	0xaf
#define Option_for_extension     	0xb0
#define Equal_button     	0xb1
#define inline_help     	0xb2
#define Log/Undo/     	0xb3
#define Toolbar_commands     	0xaa
#define reset_button     	0xb5
#define Files_Filter_scroll_list     	0xb6
#define Add_a_counter     	0xb7
#define Counter_begin's_value     	0xb8
#define Counter__step_value     	0xb9
#define Counter____digits     	0xba
#define Counter__representation     	0xbb
#define Counter__position     	0xbc
#define Add_files     	0xbd
#define Search_And_Replace_button     	0xb4
#define File's_date     	0xbf
#define File's_date__position     	0xc0
#define File's_size     	0xc1
#define File's_size__position     	0xc2
#define Folder's_name_button     	0xc3
#define Replace_with_text_check_bow     	0xc4
#define Repalce_with_text__textbox     	0xc5
#define Cyclic_selection__button     	0xc6
#define Add_text_check_box     	0xc7
#define File's_siez__position     	0xbe
#define Print_button     	0x67
#define copy_button     	0x68
#define button_save_as     	0x69
#define find_conflicts_button     	0x6a
#define preview_-_ok_button     	0x6b
#define preview_-_files_list     	0x6c
#define conflicts_ba     	0x6d
#define free_form__file_content     	0xd3
#define rename_from_a_list__the_list     	0xd4
#define rename_from_a_list__remove_button     	0xd5
#define rename_from_a_list     	0xd6
#define rename_from_alist__save_as_button     	0xd7
#define rename_from_a_list__copy_selected     	0xd8
#define rename_from_a_list__copy_all_button     	0xd9
#define rename_with_file's_content     	0xda
#define Adv_search__search_from_left_or_right     	0xdb
#define free_from__counter_step     	0xd2
#define Adv_search__search_string     	0xdd
#define Adv_search__replace_with_string     	0xde
#define Adv_Search__match_case     	0xdf
#define Adv_search__replace_all     	0xe0
#define Adv_search_character_list     	0xe1
#define Personal_date_format__command_line     	0xe2
#define Personnal_date_format__list_of_functions     	0xe3
#define Personnal_date_format__inline_help     	0xe4
#define Personnal_date_format__direct_view     	0xe5
#define Adv_Search__from_to     	0xdc
#define Personnal_date_format__default_button     	0xe7
#define Add_Folder's_name     	0xe8
#define preview_windows__validate_button     	0xe9
#define Preview_window__print_button     	0xea
#define preview_window__copy_button     	0xeb
#define preview_window_     	0xec
#define preview_windows__find_conflicts_button     	0xed
#define Free_form__examples     	0xee
#define Preview_window__files_list     	0xef
#define Personnal_date_format__help_for_one_command     	0xe6
#define Example_5     	0xf1
#define How_to_rename_folderrs     	0xf4
#define How_to_add_to_add_music_informations_from_MP3_files?     	0xf5
#define How_to_find_file_names_longer_than_64_characters?     	0xf6
#define I've_selected_to_add_a_counter_to_my_files_but_I_can't_see_padding_zeros_?     	0xf7
#define Generate_HTML_report     	0xf8
#define Organize_your_commands     	0xf9
#define Example_4     	0xf0
#define list_of_commands     	0xfb
#define Command's_description     	0xfd
#define Modify_Button_1     	0xfe
#define Use_now_button     	0xff
#define Delete_button_1     	0x100
#define Default_command's_button     	0x101
#define Clear_default_command's_button     	0x102
#define Info_buton     	0x103
#define Organize_Button     	0xfa
#define Current_command_textbox     	0x105
#define Add_to_list_button     	0x106
#define Up_button_2     	0x107
#define Down_button     	0x108
#define Regular_Expression__Definition     	0x109
#define Abbreviations     	0x10a
#define abreviation_text     	0x10b
#define substitution_text     	0x10c
#define starting_position     	0x10d
#define Close_button     	0x104
#define Add_button     	0x10f
#define Modify_button_2     	0x110
#define Use_regular_expression     	0x111
#define Replace_all     	0x112
#define Number_of_times     	0x113
#define Prefix_only     	0x114
#define extension_only     	0x115
#define both     	0x116
#define list_of...     	0x117
#define Match_case     	0x10e
#define save_button     	0x119
#define open_button     	0x11a
#define Natural_Sort     	0x11c
#define Change_Tab     	0x11d
#define Copy_files_names_in_clipboard_?     	0x11e
#define Create_Folders_with_Names_1     	0x11f
#define How_to_Remove_numeric_characters?     	0x120
#define How_To_List     	0x121
#define delete_button_2     	0x118
#define General_Tab     	0x123
#define Files_Filters_Tab     	0x124
#define Other_Tab     	0x125
#define Display_Tab     	0x126
#define Bin_Tab     	0x127
#define Settings_Tab     	0x128
#define Pictures_Tab     	0x129
#define Lists_Tab     	0x12a
#define How_to_move_files_in_the_files_list?     	0x12b
#define How_to_remove_registry_keys_created_by_THE_Rename     	0x122
#define Select_where_you_want_to_add_texte     	0xc9
#define Picture_width_checkbox     	0xca
#define picture_width_place     	0xcb
#define Click_this_button_for_sound_options     	0xcc
#define clear_button_free_form     	0xcd
#define free_from__command_line     	0xce
#define free_from__listbox     	0xcf
#define free_form__inline_help     	0xd0
#define free_form__counter's_begin     	0xd1
#define Add_text__textbox     	0xc8
#define Music_commands_for_MP3_files     	0x137
#define Music_commands_for_VQF_files     	0x138
#define Index_of_all_commands     	0x139
#define Counters_Commands     	0x13a
#define Commands_on_date_and_time     	0x13b
#define General_Commands     	0x13c
#define <curprefix_     	0x13d
#define <PRAfter_     	0x13e
#define <PRBefore_     	0x13f
#define Music_Commands     	0x136
#define <PRCapital_     	0x142
#define <PRCapitalEx_     	0x143
#define <PRCapitalFirst_     	0x144
#define <PRCowboys_     	0x145
#define <PRIfEmpty_     	0x146
#define <PRInvert_     	0x147
#define <PRInvertEX_     	0x148
#define <PRLeft_     	0x149
#define <PRBetween_     	0x140
#define <PRLower_     	0x14b
#define <PRLowerEX_     	0x14c
#define <PRltrim_     	0x14d
#define <PRMiddle_     	0x14e
#define <PRPaddLeft_     	0x14f
#define <PRPaddRight_     	0x150
#define <PRRefomartNumber_     	0x151
#define <PRRemIntSp_     	0x152
#define <PRRemMultSp_     	0x153
#define <PRLength_     	0x14a
#define <PRrtrim_     	0x155
#define <PRSepThousands_     	0x156
#define <PRSepWords_     	0x157
#define <PRToggle_     	0x158
#define <PRToggleEX_     	0x159
#define <PRToken_     	0x15a
#define <PRtrim_     	0x15b
#define <PRUpper_     	0x15c
#define <PRUpperEX_     	0x15d
#define <PRright_     	0x154
#define <ShortName_     	0x15f
#define <curext_     	0x160
#define <EXAfter_     	0x161
#define <EXBefore_     	0x162
#define <EXBetween_     	0x163
#define <EXCapital_     	0x164
#define <EXCapitalEx_     	0x165
#define <EXCapitalFirst_     	0x166
#define <EXCowboys_     	0x167
#define <RandomPrefix_     	0x15e
#define <EXInvert_     	0x169
#define <EXInvertEX_     	0x16a
#define <EXLeft_     	0x16b
#define <EXLength_     	0x16c
#define <EXLower_     	0x16d
#define <EXLowerEX_     	0x16e
#define <EXltrim_     	0x16f
#define <EXMiddle_     	0x170
#define <EXPaddLeft_     	0x171
#define <ExIfEmpty_     	0x168
#define <ExRefomartNumber_     	0x173
#define <EXRemIntSp_     	0x174
#define <EXRemMultSp_     	0x175
#define <EXright_     	0x176
#define <EXrtrim_     	0x177
#define <EXSepThousands_     	0x178
#define <EXSepWords_     	0x179
#define <EXToggle_     	0x17a
#define <EXToggleEX_     	0x17b
#define <EXPaddRight_     	0x172
#define <EXtrim_     	0x17d
#define <EXUpper_     	0x17e
#define <EXUpperEX_     	0x17f
#define <copyfile_     	0x180
#define <FileAttr_     	0x181
#define <FileContent_     	0x182
#define <FileDate_     	0x183
#define <FileDateEx_     	0x184
#define <FileLength_     	0x185
#define <EXToken_     	0x17c
#define <FileTime_     	0x187
#define <FullLength_     	0x188
#define <html_     	0x189
#define <ImgInfo_     	0x18a
#define <ttfname_     	0x18b
#define <CyclicSelection_     	0x18c
#define <PathPart_     	0x18d
#define <MP3Artist_     	0x18e
#define <MP3Band_     	0x18f
#define <FileSize_     	0x186
#define Some_other_good_programs     	0x12d
#define Global_Search_&_Replace     	0x12e
#define RegExp_rename     	0x12f
#define Reg._Expressions_Tab     	0x130
#define Notes_about_Perl_Compatible_Regular_Expressions     	0x131
#define MP3Album     	0x132
#define Commands_for_the_Prefix     	0x133
#define Commands_for_the_Extension     	0x134
#define Commands_on_current_file     	0x135
#define Why_Some_files_are_named_"Copy_of...."     	0x12c
#define <MP3Genre_     	0x19b
#define <MP3GroupIdent_     	0x19c
#define <MP3InitialKey_     	0x19d
#define <MP3InvolvedPeopleList_     	0x19e
#define <MP3Isrc_     	0x19f
#define <MP3Language_     	0x1a0
#define <MP3LinkedInformation_     	0x1a1
#define <MP3Lyricist_     	0x1a2
#define <MP3MediaType_     	0x1a3
#define <MP3FileType_     	0x19a
#define <MP3NetRadioOwner_     	0x1a5
#define <MP3NetRadioStation_     	0x1a6
#define <MP3OriginalAlbum_     	0x1a7
#define <MP3OriginalArtist_     	0x1a8
#define <MP3OriginalFilename_     	0x1a9
#define <MP3OriginalLyricist_     	0x1aa
#define <MP3OriginalYear_     	0x1ab
#define <MP3PartOfASet_     	0x1ac
#define <MP3PlayListDelay_     	0x1ad
#define <MP3MixArtist_     	0x1a4
#define <MP3Publisher_     	0x1af
#define <MP3RecordingDates_     	0x1b0
#define <MP3SoftwareEncodingSettings_     	0x1b1
#define <MP3SongLength_     	0x1b2
#define <MP3SubTitle_     	0x1b3
#define <MP3SynchronizedLyric_     	0x1b4
#define <MP3TermsOfUse_     	0x1b5
#define <MP3Time_     	0x1b6
#define <MP3Title_     	0x1b7
#define <MP3PopulariMeter_     	0x1ae
#define <MP3TrackNumber_     	0x1b9
#define <MP3UnsynchronizedLyric_     	0x1ba
#define <MP3UserText_     	0x1bb
#define <MP3wwwArtist_     	0x1bc
#define <MP3wwwAudioFile_     	0x1bd
#define <MP3wwwAudioSource_     	0x1be
#define <MP3wwwCommercialInfo_     	0x1bf
#define <MP3wwwCopyright_     	0x1c0
#define <MP3wwwPayment_     	0x1c1
#define <MP3TotalTracks_     	0x1b8
#define <MP3wwwRadioPage_     	0x1c3
#define <MP3wwwUserURL_     	0x1c4
#define <MP3Year_     	0x1c5
#define <VQFArtist_     	0x1c6
#define <VQFBitrate_     	0x1c7
#define <VQFComment_     	0x1c8
#define <VQFCopyright_     	0x1c9
#define <VQFFileSaveAs_     	0x1ca
#define <VQFMonoStereo_     	0x1cb
#define <MP3wwwPublisher_     	0x1c2
#define <VQFSampleRate_     	0x1cd
#define <VQFTitle_     	0x1ce
#define <ddddd_     	0x1cf
#define <ooooo_     	0x1d0
#define <RandomNumber_     	0x1d1
#define <Textcounter_     	0x1d2
#define <xxxxx_     	0x1d3
#define <systdate_     	0x1d4
#define <SystDateEx_     	0x1d5
#define <VQFQuality_     	0x1cc
#define How_to_restore_THE_Rename's_window_to_a_normal_position_?     	0x1d7
#define Rename_with_rules     	0x1d8
#define more_options     	0x1d9
#define Tabs     	0x1da
#define <CounterEx_     	0x1db
#define P4CPZA     	0x1dc
#define Folders     	0x1dd
#define View_Log_File     	0x1df
#define <systtime_     	0x1d6
#define <PRPrevFileOldName_     	0x1e1
#define <PRPrevFileNewName_     	0x1e2
#define <EXPrevFileOldName_     	0x1e3
#define <EXPrevFileNewName_     	0x1e4
#define <PRModifyCounter_     	0x1e5
#define <EXModifyCounter_     	0x1e6
#define How_to_preview_MP3__VQF_and_OGG_tags_?     	0x1e8
#define How_to_export_tags_from_musical_files_?     	0x1e9
#define How_to_create_folders_with_names     	0x1e0
#define OggAlbum     	0x1eb
#define Note_about_Ogg_files     	0x1ec
#define OggArtist     	0x1ed
#define OggAverageBitrate     	0x1ee
#define OggChannels     	0x1ef
#define OggComment     	0x1f0
#define OggComposer     	0x1f1
#define OggConductor     	0x1f2
#define OggCopyRight     	0x1f3
#define Commands_for_OGG_files     	0x1ea
#define <MP3Comment_     	0x191
#define <MP3Composer_     	0x192
#define <MP3Conductor_     	0x193
#define <MP3ContentGroup_     	0x194
#define <MP3Copyright_     	0x195
#define <MP3Date_     	0x196
#define <MP3EncodedBy_     	0x197
#define <MP3EncryptionMethod_     	0x198
#define <MP3FileOwner_     	0x199
#define <MP3Bpm_     	0x190
#define OggNominalBitrate     	0x1ff
#define OggNumberOfTags     	0x200
#define OggOrganization     	0x201
#define OggPerformer     	0x202
#define OggPlaytime     	0x203
#define OggSampleRate     	0x204
#define OggSerialNumbe     	0x205
#define OggTagByName     	0x206
#define OggTagByPosition     	0x207
#define OggLowerBitrate     	0x1fe
#define OggTotalTracks     	0x209
#define OggTrackNumber     	0x20a
#define OggUpperBitrate     	0x20b
#define OggVendor     	0x20c
#define OggVersion     	0x20d
#define P4CQUA     	0x20e
#define EXInsert     	0x20f
#define PRRemove     	0x210
#define EXRemove     	0x211
#define OggTitle     	0x208
#define ExDeleteText     	0x213
#define How_to_make_THE_Rename_quicker_?     	0x214
#define AOEBFDK     	0x215
#define <NonSelectedFilesCount_     	0x216
#define <TotalFilesCount_     	0x217
#define <RomanCounter_     	0x218
#define P4CQVB     	0x219
#define PRDeleteText     	0x212
#define OggDescription     	0x1f5
#define OggEncoderVersion     	0x1f6
#define OggEnsemble     	0x1f7
#define OggGenre     	0x1f8
#define OggGetAllTags     	0x1f9
#define OggGetUnknowTags     	0x1fa
#define OggISRC     	0x1fb
#define OggLength     	0x1fc
#define OggLocation     	0x1fd
#define OggDate     	0x1f4
#define Help_Index     	0x1
#define What_is_THE_Rename     	0x2
#define Vocabulary     	0x3
#define Status     	0x8
#define Requirements     	0x9
#define Create_folders_with_names_2     	0x1e7
#define Suggested_uses_for_THE_Rename     	0x24
#define Bin_menu     	0x42
#define AfmFontMetricsVersion	4
#define AfmWeight	5
#define AfmNotice	6
#define AfmMetricsSets	7
#define AfmFullName	12
#define AfmFontVersion	27
#define AfmFontName	28
#define AfmFamilyName	29
#define AfmEncodingScheme	30
#define AfmCharacterSet	31
#define AfmCopyright	70
#define AfmCreationDate	71
#define AfmUniqueID	72
#define AfmVMusage	73
#define CommansdForAdobeFonts	74
#define Previous_Tab	75
#define Create_a_list_of_folders_manually	76
#define Sounds_Information	77
#define Pictures_Information	78
#define Search_for_files_in_favorites	79
#define Pictures_Previewer	80
#define ExifAperture	81
#define ExifBrightness	82
#define ExifCompressedBitsPerPixel	83
#define ExifCopyright	84
#define ExifDateTime	85
#define ExifDateTimeDigitized	86
#define ExifDateTimeOriginal	87
#define ExifVersion	88
#define ExifExposureBias	89
#define ExifExposureProgram	90
#define ExifExposureTime	91
#define ExifFirmwareVersion	92
#define ExifFlash	93
#define ExifFNumber	94
#define ExifFocalLength	95
#define ExifFocalPlaneResolutionUnit	96
#define ExifFocalPlaneXResolution	97
#define ExifFocalPlaneYResolution	98
#define ExifImageDescription	99
#define ExifImageHeight	100
#define ExifImageWidth	101
#define ExifISOSpeedRatings	102
#define ExifMake	112
#define ExifMaxAperture	145
#define ExifMeteringMode	155
#define ExifModel	160
#define ExifOrientation	163
#define ExifRelatedSoundFile	164
#define ExifResolutionUnit	242
#define ExifShutterSpeed	243
#define ExifSubjectDistance	252
#define ExifWhiteBalance	283
#define ExifXResolution	321
#define ExifYResolution	478
#define PrBeforEx	538
#define WmaChannelMode	539
#define WmaSampleRate	540
#define WmaDuration	541
#define WmaBitRate	542
#define WmaTrack	543
#define WmaTitle	544
#define WmaArtist	545
#define WmaAlbum	546
#define WmaGenre	547
#define WmaComment	548
#define WmaYear	549
#define For_WMA_files	550
#define Commands_for_pictures	551
#define Donation	552
#define My_other_programs	553
